language: python
dist: xenial
python:
  - "3.6"
  - "3.7.3"
  - "3.8"
  - "3.9"

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install --upgrade flake8 cfn_flip>=1.0.2

before_script:
  - flake8 --version
  - flake8 . --show-source 

script:
  - python setup.py test
